FROM python:3.10.6-buster

#WORKDIR /prod

RUN pip install --upgrade pip

COPY requirements_deploy.txt requirements_deploy.txt

RUN pip install -r requirements_deploy.txt

COPY detector detector
COPY setup.py  setup.py
COPY models/gpt3_output/demo_data.csv models/gpt3_output/demo_data.csv
COPY models/extractors_model_google-electra-large-discriminator models/extractors_model_google-electra-large-discriminator
COPY models/extractors_tokenizer_google-electra-large-discriminator models/extractors_tokenizer_google-electra-large-discriminator
COPY models/nn_model_google-electra-large-discriminator_70000 models/nn_model_google-electra-large-discriminator_70000
COPY models/trained_models_70000 models/trained_models_70000
# RUN pip install .

CMD uvicorn detector.api.fast:app --host 0.0.0.0 --port $PORT
